old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            keepalive: true
            heartbeat: 0
            use_socket: true # default false
    producers:
        payment:
            connection:       default
            exchange_options: {name: 'payment', type: direct}
            service_alias:    payment_service # no alias by default
    consumers:
        payment:
            connection:       default
            exchange_options: {name: 'payment', type: direct}
            queue_options:    {name: 'payment'}
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
            callback:         AppBundle\Exchange\PaymentConsumer