indexx:
    path:     /
    methods:  ['GET']
    defaults: { _controller: AppBundle:Default:index }

calculate:
    path:     /calculate
    methods:  ['POST']
    defaults: { _controller: AppBundle:Default:calculate }
